import AmethystDevLogo from "@/components/Blog/AmethystDevLogo";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Amethyst Dev Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className="bg-main flex flex-col justify-center items-center">
        <header className="bg-main p-5 flex justify-between items-center sticky top-0 w-screen lg:w-[50rem] md:w-[35rem] ">
          <AmethystDevLogo />
          <div className=" ">
            <Link href={"/blog"}>
              <button className="w-[80px] px-5 py-3 rounded-md mr-2 text-white hover:bg-dark_purple_01">
                Home
              </button>
            </Link>
            <Link href={"/sobre-nos"}>
              <button className="w-[80px] px-5 py-3 rounded-md mr-2 text-white hover:bg-dark_purple_01">
                Sobre
              </button>
            </Link>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
